version: "3"

services:
  db:
    container_name: ${BASE_NAME_SERVICE}_db
    build:
      context: ./
      dockerfile: docker/db.Dockerfile
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - default

  redis:
    container_name: ${BASE_NAME_SERVICE}_redis
    image: redis:5.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - default

  app:
    container_name: ${BASE_NAME_SERVICE}_app
    build:
      context: ./
      dockerfile: docker/app.Dockerfile
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      - ./docker/config/php.ini:/usr/local/etc/php/php.ini
      - ~/.bash_history:/home/docker-user/.bash_history
    depends_on:
      - db
      - redis
    networks:
      - default
    dns:
      - 8.8.8.8

  web:
    container_name: ${BASE_NAME_SERVICE}_web
    build:
      context: ./
      dockerfile: docker/web.Dockerfile
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage
      - ./docker/config/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - default
#Docker Networks
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28