version: "3"

services:
  db:
    container_name: ${BASE_NAME_SERVICE}_db
    image: dev.zetest.site:22229/projects/legrang_db:latest
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    container_name: ${BASE_NAME_SERVICE}_redis
    image: redis:5.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]

  app:
    container_name: ${BASE_NAME_SERVICE}_app
    image: dev.zetest.site:22229/projects/legrang_app:latest
    volumes:
      - ./:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      - ./docker/config/php.ini:/usr/local/etc/php/php.ini
      - ~/.bash_history:/home/docker-user/.bash_history
    depends_on:
      - db
      - redis

  web:
    container_name: ${BASE_NAME_SERVICE}_web
    image: dev.zetest.site:22229/projects/legrang_web:latest
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage
      - ./docker/config/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
