#!/bin/bash

COMPOSE_PROJECT_NAME="legweb"

PROJECT=`docker exec -i ${COMPOSE_PROJECT_NAME}_app_1 php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
	oIFS=$IFS
	IFS='
	'
	SFILES="$1"
	IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
	docker exec -i ${COMPOSE_PROJECT_NAME}_app_1 php -l -d display_errors=0 $PROJECT/$FILE
	if [ $? != 0 ]
	then
		echo "Fix the error before commit."
		exit 1
	fi
	FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
	echo "Running Code Sniffer..."
	docker exec -i ${COMPOSE_PROJECT_NAME}_app_1 /var/www/vendor/bin/phpcs --encoding=utf-8 -p $FILES
	if [ $? != 0 ]
	then
		echo "Coding standards errors have been detected. Fix it before commit..."
		exit 1
	fi
fi

echo "Running Code Analysis..."

docker exec -i ${COMPOSE_PROJECT_NAME}_app_1 php artisan code:analyse
if [ $? != 0 ]
then
    echo "Coding standards errors have been detected. Fix it before commit..."
    exit 1
fi

exit $?
